return {
    "vehicul",
    --regular
    "Bike",
    "Faggio",
    "BMX",
    "Perennial",
    "Benson",
    "Picador",
    "Pony",
    "Mountain Bike",
    "Rumpo",
    "Moonbeam",
    "Camper",
    "Sadler",
    "Walton",
    "Regina",
    "Bravura",
    "Oceanic",
    "Willard",
    "Glendale",
    "Hermes",
    "Manana",
    "Quad",
    "Intruder",
    "Berkley's RC Van",
    "Fortune",
    "Primo",
    "Previon",
    "Virgo",
    "Majestic",
    "Bobcat",
    "Cadrona",
    "Sunrise",
    "Burrito",
    "Solair",
    "Mesa",
    "Journey",
    "Emperor",
    "Merit",
    "Landstalker",
    "Nebula",
    "Esperanto",
    "Stallion",
    "Stafford",
    "Clover",
    "Tampa",
    "Hotknife",
    "Hustler",
    "Blista Compact",
    "Greenwood",
    "Vincent",
    "Stratum",
    "Elegant",
    "Washington",
    "Broadway",
    "Tahoma",
    "Savanna",
    "Buccaneer",
    "Tornado",
    "Slamvan",
    "Yosemite",
    "Windsor",
    "Remington",
    "Wayfarer",
    "Bloodring Banger",
    "Premier",
    "Club",
    "Phoenix",
    "Rancher",
    "Freeway",
    "Sabre",
    "Blade",
    "Feltzer",
    "Sentinel",
    "Admiral",
    "Euros",
    "Voodoo",
    "Sanchez",
    "Alpha",
    "Huntley",
    "Uranus",
    "Flash",
    "Comet",
    "BF-400",
    "Super GT",
    "PCJ-600",
    "FCR-900",
    "ZR-350",
    "Jester",
    "Buffalo",
    "Elegy",
    "Sandking",
    "Cheetah",
    "Banshee",
    "Turismo",
    "Sultan",
    "Bullet",
    "NRG-500",
    "Infernus",

    -- premium
    "Patriot",
    "Sparrow",
    "Hotring Racer A",
    "Hotring Racer B",
    "Hotring Racer",
    "Vortex",
    "Maverick",

    -- special
    "Stretch",
    "Mr Whoopee",
    "BF Injection",
    "Romero",
    "Caddy",
    "FBI Rancher",
    "Jetmax",
    "Bandito",
    "Kart",
}

-- local no_use =  {

--     -- none = "none",

--     veh = "vehicul",
--     vehvip = "vehicul",    

--     -- regular
--     bike = "Bike",
--     faggio = "Faggio",
--     bmx = "BMX",
--     perennial = "Perennial",
--     benson = "Benson",
--     picador = "Picador",
--     pony = "Pony",
--     mtb = "Mountain Bike",
--     rumpo = "Rumpo",
--     moonbeam = "Moonbeam",
--     camper = "Camper",
--     sadler = "Sadler",
--     walton = "Walton",
--     regina = "Regina",
--     bravura = "Bravura",
--     oceanic = "Oceanic",
--     willard = "Willard",
--     glendale = "Glendale",
--     hermes = "Hermes",
--     manana = "Manana",
--     quad = "Quad",
--     intruder = "Intruder",
--     van = "Berkley's RC Van",
--     fortune = "Fortune",
--     primo = "Primo",
--     previon = "Previon",
--     virgo = "Virgo",
--     majestic = "Majestic",
--     bobcat = "Bobcat",
--     cadrona = "Cadrona",
--     sunrise = "Sunrise",
--     burrito = "Burrito",
--     solair = "Solair",
--     mesa ="Mesa",
--     journey = "Journey",
--     emperor = "Emperor",
--     merit = "Merit",
--     land = "Landstalker",
--     nebula = "Nebula",
--     esperanto ="Esperanto",
--     stallion = "Stallion",
--     stafford = "Stafford",
--     clover = "Clover",
--     tampa = "Tampa",
--     hotknife = "Hotknife",
--     hustler = "Hustler",
--     blista = "Blista Compact",
--     greenwood = "Greenwood",
--     vincent = "Vincent",
--     stratum = "Stratum",
--     elegant = "Elegant",
--     washington = "Washington",
--     broadway = "Broadway",
--     tahoma = "Tahoma",
--     savanna = "Savanna",
--     buccaneer = "Buccaneer",
--     tornado = "Tornado",
--     slamvan = "Slamvan",
--     yosemite = "Yosemite",
--     windsor = "Windsor",
--     remington = "Remington",
--     wayfarer = "Wayfarer",
--     banger = "Bloodring Banger",
--     premier = "Premier",
--     club = "Club",
--     phoenix = "Phoenix",
--     rancher = "Rancher",
--     freeway = "Freeway",
--     sabre = "Sabre",
--     blade = "Blade",
--     feltzer = "Feltzer",
--     sentinel = "Sentinel",
--     admiral = "Admiral",
--     euros = "Euros",
--     voodoo = "Voodoo",
--     sanchez = "Sanchez",
--     alpha = "Alpha",
--     huntley = "Huntley",
--     uranus = "Uranus",
--     flash = "Flash",
--     comet = "Comet",
--     bf400 = "BF-400",
--     gt = "Super GT",
--     pcj = "PCJ-600",
--     fcr = "FCR-900",
--     zr = "ZR-350",
--     jester = "Jester",
--     buffalo ="Buffalo",
--     elegy = "Elegy",
--     sandking = "Sandking",
--     cheetah = "Cheetah",
--     banshee = "Banshee",
--     turismo = "Turismo",
--     sultan = "Sultan",
--     bullet = "Bullet",
--     nrg= "NRG-500",
--     inf = "Infernus",

--     -- premium
--     patriot = "Patriot",
--     sparrow = "Sparrow",
--     hota = "Hotring Racer A",
--     hotb = "Hotring Racer B",
--     hot = "Hotring Racer",
--     vortex = "Vortex",
--     mave = "Maverick",

--     -- special
--     stretch = "Stretch",
--     mr = "Mr Whoopee",
--     bfi = "BF Injection",
--     romero = "Romero",
--     caddy = "Caddy",
--     fbi = "FBI Rancher",
--     jetmax = "Jetmax",
--     bandito = "Bandito",
--     kart = "Kart",

--     -- vip
--     infvip = "Infernus VIP",
--     sultanvip = "Sultan VIP",
--     bulletvip = "Bullet VIP",
--     jestervip = "Jester VIP",
--     jetmaxvip = "Jetmax VIP"
-- }